spring:
 application:
  name: food-services


 datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5433/hiberjpa
  username: postgres
  password: "{cipher}5abacd8eb5b050f0ab0d5fefcae4b591c76ac86cf60a2136dfd02b51ae47d6a0"

 jpa:
  hibernate:
   ddl-auto: create
  properties:
   hibernate:
    default_schema: foodschema


server:
 port: 8084

eureka:
 client:
  service-url:
   defaultZone: http://localhost:5000/eureka/



